site_name: About OldInsuranceMaps.net
site_url: https://oldinsurancemaps.net
site_dir: .docs
extra_css:
  - _assets/stylesheets/extra.css
extra:
  homepage: https://oldinsurancemaps.net
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
plugins:
  - search
  - glightbox:
      auto_caption: true
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: custom
    # accent: custom
  font:
    text: Josefin Sans
  logo: _assets/images/colored-full-linework.png
  favicon: _assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
nav:
  - Home:
    - 'index.md'
    - 'community.md'
    - 'faq.md'
    - 'sanborn-maps.md'
    - 'background.md'
    - 'credits.md'
  - Guides: 
    - 'guides/index.md'
    - 'guides/browsing.md'
    - 'guides/viewer.md'
    - 'guides/preparation.md'
    - 'guides/georeferencing.md'
    - 'guides/trimming.md'
  - 'tutorial.md'
  - Go to OldInsuranceMaps.net &rarr;: 'https://oldinsurancemaps.net'
